# Generated by Django 5.0.2 on 2024-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(default=None, null=True, upload_to='')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
