# Generated by Django 5.0.2 on 2024-02-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.CharField(default='', max_length=100),
        ),
    ]
