# Generated by Django 5.0.2 on 2024-02-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colors', models.CharField(default='', max_length=100)),
                ('img', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
