# Generated by Django 5.0.2 on 2024-02-24 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_commander_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='v1.player'),
            preserve_default=False,
        ),
    ]
