# Generated by Django 5.0.2 on 2024-02-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_commander_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='player',
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colors', models.CharField(default='', max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.player')),
            ],
        ),
        migrations.AddField(
            model_name='commander',
            name='deck',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='v1.deck'),
        ),
    ]
