# Generated by Django 5.0.2 on 2024-02-27 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_remove_commander_player_deck_commander_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
