# Generated by Django 5.0.2 on 2024-02-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_deck_created_date_deck_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
