# Generated by Django 5.0.2 on 2024-02-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_pod_game_podplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.player'),
        ),
        migrations.AlterField(
            model_name='podplayer',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.pod'),
        ),
        migrations.AlterField(
            model_name='podplayer',
            name='total_win_perc',
            field=models.FloatField(default=0),
        ),
    ]
