# Generated by Django 5.0.2 on 2024-03-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_alter_podplayer_player_alter_podplayer_pod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='loser',
        ),
        migrations.AddField(
            model_name='game',
            name='losers',
            field=models.ManyToManyField(related_name='lost_games', to='v1.deck'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_log',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
