# Generated by Django 5.0.2 on 2024-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_remove_game_losers_alter_game_decks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podplayer',
            name='kil_avg',
        ),
        migrations.AddField(
            model_name='player',
            name='games_as_arch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='kill_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_win_perc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins_as_arch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podplayer',
            name='kill_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_log',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
