# Generated by Django 5.0.2 on 2024-08-11 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_remove_podplayer_kil_avg_player_games_as_arch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='wins',
            new_name='total_wins',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='commander',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='created_date',
        ),
        migrations.AddField(
            model_name='commander',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='cmdr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.commander'),
        ),
        migrations.AddField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_type',
            field=models.CharField(choices=[('commander', 'COMMANDER'), ('standard', 'STANDARD'), ('modern', 'MODERN'), ('pioneer', 'PIONEER')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='tcg',
            field=models.CharField(choices=[('magic_the_gathering', 'MAGIC'), ('one_piece', 'ONE_PIECE')], default='magic_the_gathering', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod',
            name='pod_tcg',
            field=models.CharField(choices=[('magic_the_gathering', 'MAGIC'), ('one_piece', 'ONE_PIECE')], default='magic_the_gathering', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='podplayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podplayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commander',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
