# Generated by Django 5.0.2 on 2024-08-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_rename_wins_deck_total_wins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cmdr',
        ),
        migrations.AddField(
            model_name='commander',
            name='deck',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='v1.deck'),
        ),
    ]
