# Generated by Django 5.0.2 on 2024-08-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_remove_deck_cmdr_commander_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commander',
            old_name='img',
            new_name='photo',
        ),
    ]
