# Generated by Django 5.0.2 on 2024-08-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_rename_img_commander_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='tcg',
            new_name='tcg_type',
        ),
        migrations.RenameField(
            model_name='pod',
            old_name='pod_tcg',
            new_name='tcg_type',
        ),
    ]
