# Generated by Django 5.0.2 on 2024-08-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_rename_tcg_deck_tcg_type_rename_pod_tcg_pod_tcg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podplayer',
            old_name='games_as_arch',
            new_name='games_as_archenemy',
        ),
        migrations.RenameField(
            model_name='podplayer',
            old_name='kill_avg',
            new_name='kill_average',
        ),
        migrations.RenameField(
            model_name='podplayer',
            old_name='total_win_perc',
            new_name='total_win_percentage',
        ),
        migrations.RenameField(
            model_name='podplayer',
            old_name='wins_as_arch',
            new_name='wins_as_archenemy',
        ),
    ]
