# Generated by Django 5.0.2 on 2024-08-13 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_rename_games_as_arch_podplayer_games_as_archenemy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kill_avg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_win_perc',
        ),
        migrations.RemoveField(
            model_name='podplayer',
            name='kill_average',
        ),
        migrations.RemoveField(
            model_name='podplayer',
            name='total_win_percentage',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_log',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('is_archenemy', models.BooleanField(default=False)),
                ('kills', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.deck')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.player')),
            ],
        ),
    ]
