# Generated by Django 5.0.2 on 2024-08-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_remove_game_decks_remove_player_kill_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_turns',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
