# Generated by Django 5.0.2 on 2024-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_game_total_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_log',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
