# Generated by Django 5.0.2 on 2024-08-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_alter_game_game_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
