# Generated by Django 5.0.2 on 2024-08-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_remove_game_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='games_as_arch',
            new_name='games_as_archenemy',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='wins_as_arch',
            new_name='wins_as_archenemy',
        ),
    ]
